#!/usr/bin/env bash
# Installing nginx web server
# Nginx should be listening on port 80

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
