#!/usr/bin/env bash

# Bash script to debug and restore the default server port
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
